
Theoretical Questions:


Question 1:>>  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans 1:>> NumPy, short for Numerical Python, is a fundamental library for scientific computing and data analysis in Python.

Purpose of NumPy:

1:Efficient Array Computations: NumPy provides support forr large,multidimensional array and matrices, along with a collection of mathematical functions to operate on these arrays.

2: Foundation of other libaries: Many other scientific computing and data analysis libraries, such as Pandas, SciPy, and Matplotlib, are built on top of NumPy

Advantages of NumPy
1.performance
2.Memory Efficiency
3.Vectorization
4.Broadcasting




Question 2:>>  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other

Ans 2: Both np.mean() and np.average() in NumPy are used to calculate the average of array elements, but they have some key differences and specific use cases:

1> np.mean()
Purpose: Calculates the arithmetic mean (average) of the elements in an array.

Usage: np.mean(array, axis=None)

Weights: Does not support weights; all elements are considered equally.

2> np.average()
Purpose: Calculates the weighted average if weights are provided; otherwise, it calculates the arithmetic mean.

Usage: np.average(array, axis=None, weights=None)

Weights: Supports weights, allowing for the calculation of a weighted average.





Question 3:>Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

Ans 3:> Methods of reversing a numpy array

1: Using np.flip()

This function reverses the order of elements in an array along the specified axis.

Syntax: np.flip(array,axis)


2: Using np.flipud() and np.fliplr():

np.flipud() flips an array vertically (up/down).
np.fliplr() flips an array horizontally (left/right).


3: Using array slicing :    

you can reverse an array using slicing with [::-1]


In [5]:
# example  using np.flip()

# 1d array

import numpy as np

arr_1d=np.array([1,2,3,4,5])

reversed_1d=np.flip(arr_1d)
print("original array is ",arr_1d)

print("Reversed array is: ",reversed_1d)


# 2d array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

reversed_2d=np.flip(arr_2d,axis=0)
print("Original 2darray is: ",arr_2d)
print("Reversed 2d array is: ",arr_2d)


original array is  [1 2 3 4 5]
Reversed array is:  [5 4 3 2 1]
Original 2darray is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2d array is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Using flipud() and fliplr()
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_ud = np.flipud(arr_2d)  # Flip up/down
flipped_lr = np.fliplr(arr_2d)  # Flip left/right
print("Original 2D array:\n", arr_2d)
print("Flipped up/down:\n", flipped_ud)
print("Flipped left/right:\n", flipped_lr)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped up/down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped left/right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [10]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_1d)

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d_axis0 = arr_2d[::-1, :]  # Reverse along rows
reversed_2d_axis1 = arr_2d[:, ::-1]  # Reverse along columns
print("Original 2D array:\n", arr_2d)
print("Reversed along axis 0 (rows):\n", reversed_2d_axis0)
print("Reversed along axis 1 (columns):\n", reversed_2d_axis1)


Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along axis 0 (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along axis 1 (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Question 4:  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance

Ans 4: in numpy array we can determine the data type of element in an array using the .dtype


Importance of Data Types in Memory Management and Performance:


1.Memory Efficiency: Data types in numpy define (in bytes) of the elements in the array.
2.Performance:> numpy arrays are stored in contiguous blocks of memory , making operations on them faster

3.Consistency and Compatibility: in scientific computing,its cruicial to maintain consistency across data types for operations like matrix multiplication or element-wise operations


In [1]:
# example of .dtype
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


Question 5:  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans 5: An ndarray (short for N-dimensional array) is the core data structure in NumPy. It is a multi-dimensional container for homogeneous data, meaning all elements in an ndarray must be of the same data type

key Features of ndarray:

1.Multi-Dimensional

2.Homogeneous Data

3. Efficient memory usage

Differences Between ndarray and Python Lists:>>

1.Data Type Consistency:
ndarray: All elements must be of the same data type.
Python Lists: Can contain elements of different data types.

2.Functionality:
ndarray: Supports a wide range of mathematical and statistical operations directly.

Python Lists: Requires additional libraries or manual implementation for advanced numerical operations.




In [11]:
#example
import numpy as np

# Creating an ndarray
arr = np.array([1, 2, 3, 4, 5])
print("ndarray:", arr)
print("Data type:", arr.dtype)

# Creating a Python list
lst = [1, 2, 3, 4, 5]
print("Python list:", lst)
print("Data type:", type(lst[0]))


ndarray: [1 2 3 4 5]
Data type: int64
Python list: [1, 2, 3, 4, 5]
Data type: <class 'int'>


Question 6:  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans 6: NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. Here are some key reasons why:


1.memory efficiency
2.Performance
3.Advanced mathmatical functions




In [12]:
# example
import numpy as np
import time

# Using a Python list
size = 1000000
py_list = list(range(size))
start_time = time.time()
py_list = [x * 2 for x in py_list]
end_time = time.time()
print("Time taken using Python list:", end_time - start_time)

# Using a NumPy array
np_array = np.arange(size)
start_time = time.time()
np_array = np_array * 2
end_time = time.time()
print("Time taken using NumPy array:", end_time - start_time)


Time taken using Python list: 0.2919611930847168
Time taken using NumPy array: 0.031565189361572266


Question 7: Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans 7: The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively


1. np.vstack()

 Purpose: Stacks arrays in sequence vertically (row-wise)

Usage: np.vstack(tup)



2. np.hstack()

Purpose: Stacks arrays in sequence horizontally (column-wise)

Usage: np.hstack(tup)


In [13]:
# example np.vstack()

import numpy as np

# 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked_1d = np.vstack((a, b))
print("vstacked 1D arrays:\n", vstacked_1d)

# 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vstacked_2d = np.vstack((a, b))
print("vstacked 2D arrays:\n", vstacked_2d)


vstacked 1D arrays:
 [[1 2 3]
 [4 5 6]]
vstacked 2D arrays:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
# example of np.hstack()
import numpy as np

# 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
hstacked_1d = np.hstack((a, b))
print("hstacked 1D arrays:\n", hstacked_1d)

# 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
hstacked_2d = np.hstack((a, b))
print("hstacked 2D arrays:\n", hstacked_2d)

hstacked 1D arrays:
 [1 2 3 4 5 6]
hstacked 2D arrays:
 [[1 2 5 6]
 [3 4 7 8]]


Question 8: Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans 8:

1. np.fliplr()
Purpose: Flips the array in the left/right direction (horizontally)

Axis: Operates along axis 1 (columns)

Usage: np.fliplr(array)

Effect: Reverses the order of elements in each row, while the rows themselves remain in the same order.


2.np.flipud()
Purpose: Flips the array in the up/down direction (vertically)

Axis: Operates along axis 0 (rows)

Usage: np.flipud(array)

Effect: Reverses the order of rows, while the columns themselves remain in the same order.


In [15]:
# example fliplr()
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_lr = np.fliplr(arr_2d)
print("Original 2D array:\n", arr_2d)
print("Flipped left/right:\n", flipped_lr)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped left/right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [16]:
# example of flipud
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_ud = np.flipud(arr_2d)
print("Original 2D array:\n", arr_2d)
print("Flipped up/down:\n", flipped_ud)



Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped up/down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Question 9:  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans: The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to divide an array into sections that may not be of equal size.


Functionality of array_split()

Syntax: np.array_split(ary, indices_or_sections, axis=0)






In [17]:
# example
import numpy as np

# 1D array
arr = np.arange(9)
# Split into 4 parts
split_arr = np.array_split(arr, 4)
print("Original array:", arr)
print("Split arrays:", split_arr)


Original array: [0 1 2 3 4 5 6 7 8]
Split arrays: [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


Question 10:  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations

Ans 10:
 Vectorization in NumPy:>>Vectorization refers to the process of performing operations on entire arrays without the need for explicit loops


Broadcasting in NumPy:Broadcasting describes how NumPy handles arrays with different shapes during arithmetic operations. When performing operations on arrays of different shapes, NumPy automatically expands the smaller array to match the shape of the larger array without making unnecessary copies of data

In [18]:
# example  of vectorization

import numpy as np

# Using a loop
arr = np.array([1, 2, 3, 4, 5])
result_loop = []
for x in arr:
    result_loop.append(x * 2)
result_loop = np.array(result_loop)
print("Result using loop:", result_loop)

# Using vectorization
result_vectorized = arr * 2
print("Result using vectorization:", result_vectorized)


Result using loop: [ 2  4  6  8 10]
Result using vectorization: [ 2  4  6  8 10]


In [19]:
# using Broadcasting
import numpy as np

# Arrays of different shapes
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

# Broadcasting
result = a + b
print("Array a:\n", a)
print("Array b:\n", b)
print("Result of broadcasting:\n", result)



Array a:
 [1 2 3]
Array b:
 [[1]
 [2]
 [3]]
Result of broadcasting:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


PRACTICAL QUESTIONS:


Question 1:Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [30]:
arr=np.random.randint(1,100,(3,3))
print('original numpy array is: ')
print(arr)

# interchange
print("After interchange array is :")

print(arr.T)


original numpy array is: 
[[28 89 63]
 [90 84 35]
 [62 65 37]]
After interchange array is :
[[28 90 62]
 [89 84 65]
 [63 35 37]]


Question 2:  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [40]:
arr_1d=np.arange(10)
print("original 1d_array is :")
print(arr_1d)
print()
print("after reshape array is :")
arr_1d.reshape(2,5)

original 1d_array is :
[0 1 2 3 4 5 6 7 8 9]

after reshape array is :


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Question 3: Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [12]:
import numpy as np
arr_4 = np.random.rand(4,4)
print("Original array 4*4:\n",arr_4)

#add border of zeros around the 4*4

arr_6=np.pad(arr_4,pad_width=1,mode='constant',constant_values=0)

print("6*6 array with border of zeros:\n",arr_6)

Original array 4*4:
 [[0.37045898 0.97003021 0.11714076 0.22313417]
 [0.10093392 0.37191699 0.31090105 0.94375339]
 [0.58954702 0.03001273 0.99329302 0.61170616]
 [0.78219597 0.99391658 0.85023313 0.50848103]]
6*6 array with border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.37045898 0.97003021 0.11714076 0.22313417 0.        ]
 [0.         0.10093392 0.37191699 0.31090105 0.94375339 0.        ]
 [0.         0.58954702 0.03001273 0.99329302 0.61170616 0.        ]
 [0.         0.78219597 0.99391658 0.85023313 0.50848103 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Question 4: Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [59]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 60, 5)
print("Array from 10 to 60 with step 5:", array)


Array from 10 to 60 with step 5: [10 15 20 25 30 35 40 45 50 55]


Question 5:  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [22]:
import numpy as np
str_lst=['python','numpy','pandas']
upper_case=np.char.upper(str_lst)
print("Uppercase: ",upper_case)

# into lowecase

lower_case= np.char.lower(str_lst)
print("Lowercase: ",lower_case)

#into title
title_arr=np.char.title(str_lst)
print("Title: ",title_arr)

#swap case:

swapcase_arr=np.char.swapcase(str_lst)
print("Swapcase: ",swapcase_arr)

Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:  ['python' 'numpy' 'pandas']
Title:  ['Python' 'Numpy' 'Pandas']
Swapcase:  ['PYTHON' 'NUMPY' 'PANDAS']


Question 6: Generate a NumPy array of words. Insert a space between each character of every word in the array

In [27]:
import numpy as np

# Step 1: Create the NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])
print("Original array:", words)

# Step 2: Insert a space between each character of every word
def insert_spaces(word):
    return ' '.join(list(word))

spaced_words = np.array([insert_spaces(word) for word in words])
print("Array with spaces between characters:", spaced_words)


Original array: ['python' 'numpy' 'pandas']
Array with spaces between characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


Question 7:  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [31]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
print("Array 1:\n", array1)
print("Array 2:\n", array2)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]


In [33]:
# addition
addition = np.add(array1,array2)
print("Element-wise  Addition:\n",addition)

Element-wise  Addition:
 [[ 8 10 12]
 [14 16 18]]


In [36]:
# subtract
subtraction=np.subtract(array1,array2)
print("Element-wise Subtraction:\n",subtraction)

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]


In [38]:
# multiply
multiplication= np.multiply(array1,array2)
print("Element-wise multiplication:\n",multiplication)

Element-wise multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [39]:
# Divide
division=np.divide(array1,array2)
print("Element-wise division:\n",division)

Element-wise division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Question 8: Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [48]:
import numpy as np
identity_matrix=np.eye(5)
print("5*5 identity_matrix :\n",identity_matrix)

# extract diagonal element
diagonal_element=np.diag(identity_matrix)
print("Diagonal element",diagonal_element)

5*5 identity_matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal element [1. 1. 1. 1. 1.]


Question 9:  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [55]:
array_integers=np.random.randint(0,1000,(100))
print("Random integers:\n",array_integers)

# function for prime number
def is_prime(n):
  if n<=1:
    return False

  for i in range(2,int(np.sqrt(n))+1):
    if n%i==0:
      return False
  return True

# display all prime numbers

prime_numbers=np.array([num for num in array_integers if is_prime(num)])

print("Prime numbers in the Array:\n",prime_numbers)

Random integers:
 [ 33 486 265 688 174 610 948 937 452  63  96 205 224 696 682 379 872 103
 652 719  96 300 324 328 194 241 143 459 813 931 735  76 858 976 620 445
  38 544 841 219 727 238 854 791 711 433 702 516 299 745 689 608 855 523
 566 460 866 857 693 543 819  11 347 152 766  91 990 854 332 488 340 170
 347 637  64 225 716 722 178 206 123 208 545 348 253 904 820 958 629 825
  75 534 333 478 686 268 221 770 476 624]
Prime numbers in the Array:
 [937 379 103 719 241 727 433 523 857  11 347 347]


Question 10:Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [63]:
import numpy as np

# Step 1: Create the NumPy array of daily temperatures
daily_temperatures = np.random.randint(15, 35, size=30)  # Random temperatures between 15°C and 35°C
print("Daily Temperatures:\n", daily_temperatures)

# Step 2: Calculate the weekly averages
weekly_temperatures = np.array_split(daily_temperatures, 4)  # Split into 4 weeks
weekly_averages = [np.mean(week) for week in weekly_temperatures]  # Calculate weekly averages
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [34 18 20 15 23 24 18 23 18 33 32 19 15 16 34 18 24 26 26 20 15 28 18 29
 30 20 34 17 34 31]
Weekly Averages:
 [21.875, 23.125, 22.428571428571427, 27.857142857142858]
